{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshift-routes.fullname" . }}
  labels:
    {{- include "openshift-routes.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "openshift-routes.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - name: metrics
    port: 9402
    targetPort: metrics
    protocol: TCP
{{- end }}
